[package]
name = "using_rust_with_cloud_sdk_and_cli_for_data_engineering"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
